version: "3.4"
services:
  python-runner:
    image: python_nts_scraper
    container_name: python_nts_scraper
    command: /bin/sh -c 'python nts/download_favourites.py'
    volumes:
      - /home/will/git/nts-favourites-downloader:/nts
      - /media/downloads/music/nts-shows:/downloads